import { TsuuhenCalculator } from '../../js/core/TsuuhenCalculator.js';

let calculator;

test('TsuuhenCalculator.setup', () => {
    calculator = new TsuuhenCalculator();
    assert.ok(calculator, 'Calculator instantiated');
});

test('TsuuhenCalculator.calculateTsuuhen calculates specific cases', () => {
    // 甲 (Wood Yang) vs 甲 (Wood Yang) -> 比肩 (Same Element, Same YinYang)
    let res = calculator.calculateTsuuhen('甲', '甲');
    assert.strictEqual(res.tsuuhen, '比肩');

    // 甲 (Wood Yang) vs 乙 (Wood Yin) -> 劫財 (Same Element, Different YinYang)
    res = calculator.calculateTsuuhen('甲', '乙');
    assert.strictEqual(res.tsuuhen, '劫財');

    // 甲 (Wood Yang) vs 丙 (Fire Yang) -> 食神 (I generate, Same YinYang)
    res = calculator.calculateTsuuhen('甲', '丙');
    assert.strictEqual(res.tsuuhen, '食神');

    // 甲 (Wood Yang) vs 丁 (Fire Yin) -> 傷官 (I generate, Different YinYang)
    res = calculator.calculateTsuuhen('甲', '丁');
    assert.strictEqual(res.tsuuhen, '傷官');

    // 甲 (Wood Yang) vs 戊 (Earth Yang) -> 偏財 (I control, Same YinYang)
    res = calculator.calculateTsuuhen('甲', '戊');
    assert.strictEqual(res.tsuuhen, '偏財');

    // 甲 (Wood Yang) vs 己 (Earth Yin) -> 正財 (I control, Different YinYang)
    res = calculator.calculateTsuuhen('甲', '己');
    assert.strictEqual(res.tsuuhen, '正財');

    // 甲 (Wood Yang) vs 庚 (Metal Yang) -> 偏官 (Controlled by, Same YinYang)
    res = calculator.calculateTsuuhen('甲', '庚');
    assert.strictEqual(res.tsuuhen, '偏官');

    // 甲 (Wood Yang) vs 辛 (Metal Yin) -> 正官 (Controlled by, Different YinYang)
    res = calculator.calculateTsuuhen('甲', '辛');
    assert.strictEqual(res.tsuuhen, '正官');

    // 甲 (Wood Yang) vs 壬 (Water Yang) -> 偏印 (Generated by, Same YinYang)
    res = calculator.calculateTsuuhen('甲', '壬');
    assert.strictEqual(res.tsuuhen, '偏印');

    // 甲 (Wood Yang) vs 癸 (Water Yin) -> 正印 (Generated by, Different YinYang)
    res = calculator.calculateTsuuhen('甲', '癸');
    assert.strictEqual(res.tsuuhen, '正印');
});

test('TsuuhenCalculator.calculateForPillars returns correct structure', () => {
    const res = calculator.calculateForPillars('甲', '乙', '丙', '丁');
    // Year: 甲 vs 乙 -> 劫財
    assert.strictEqual(res.year.tsuuhen, '劫財');
    // Month: 甲 vs 丙 -> 食神
    assert.strictEqual(res.month.tsuuhen, '食神');
    // Hour: 甲 vs 丁 -> 傷官
    assert.strictEqual(res.hour.tsuuhen, '傷官');
});
